### ISSUE TITLE
Laser drill conveyors

### ISSUE THREAD

**Issue by Vojtak42** [Pointifix/AutoDrill#10]
Hello, would you be able to add option to plan conveyors or bridges for laser drills? Because when the deposit is bigger, it will plan something like [that.](https://ibb.co/48sqVXZ) Also wouldn't be better to use large power nodes? And instead of water extractors put liquid routers next to the drills?
Thank you for your mod!

**Comment by Pointifix** [comment]
Implementing that is rather complex so unfortunately I don't plan to add anything like that rn. But thank you for your suggestion 👍🏻
