### ISSUE TITLE
Optimization Quality

### ISSUE THREAD

**Issue by feddddddddd** [Pointifix/AutoDrill#13]
The lower the “Optimization Quality” value, the better the placement will be?

**Comment by Pointifix** [comment]
The higher is it. The optimization is a tree search where the tree contains all possible drill placements for that patch and the higher the optimization quality the larger the portion of the tree that is being traversed. And the configuration with the most ores covered found by the search is then the result. So if you are lucky the best configuration is found early and a higher optimization quality does not optain a better result.
