### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Sean23189** [Pointifix/AutoDrill#2]
Hello,
I have a suggestion:
It would be really useful if we could set the max amount of tiles for each drill individually, because for example the standard drill needs more total drills to fill a belt than a second tier drill does but with the current system of an universal tile limit it would place the same amount of drills regardless of if the belt is at full capacity. This brings me to the next suggestion, what if it would calculate on its own how many drills need to be placed to fill a certain belt, maybe after selecting the drill we can then select what type of belt we want to use.
Regardless of if my suggestion is taken into consideration, I want to say that this mod helped me save a lot of time and it's truly a very useful mod that I now can't live without!
Thank you.
-Sean

**Comment by Pointifix** [comment]
Hello Sean,

to understand you correctly, you would like to have the following settings per drill:

- Max Tiles
- Minimum Ores

For the 4 different drills -> 8 sliders instead of currently 4?

**Comment by Sean23189** [comment]
Yes I would like to see a "Max Tiles" setting on a per-drill basis, the "Minimum Ores" setting already exists on a per-drill basis as far as I know.

I agree on the fact that it's better to keep it simple, it was just a small thought that after consideration, doesn't seem that useful anymore.

Thank you for replying!
-Sean

**Comment by Pointifix** [comment]
added more settings 🙌🏻 
https://github.com/Pointifix/AutoDrill/releases/latest
