### ISSUE TITLE
Water Extractors

### ISSUE THREAD

**Issue by SecretMan817** [Pointifix/AutoDrill#4]
So i was messing around with this mod when i found that the it still places water extractors even though i haven't researched it yet.
here's a video: https://streamable.com/dwlkjw (sorry for stutters)
i have mods enabled but i don't think the mods are causing the bug.

**Comment by Pointifix** [comment]
You can turn off the placement of water extractors and power nodes in the settings of the mod ingame. The mod was not developed with the campaign in mind but just turn it manually off when you use it in the campaign.
